### ISSUE TITLE
segfault during benchmark

### ISSUE THREAD

**Issue by jssmith** [jssmith/ssqlite#4]
Running the benchmark command
```
vfsbench nfs4 192.168.1.57/test-1gb
```

Leads to this error once the block size reaches 16k.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6a92246 in read_beu32 (b=0x1b93000) at ./buffer.h:101
101	    u32 v = ntohl(*(u32*)(b->contents + b->start));
```

Test data file was created with
```
head -c 1073741824 /dev/urandom > /efs/test-1gb
```

**Comment by convolvatron** [comment]
there are two failures here:
   o the read result handler isn't handling server errors appropriately 
   o large reads need to be chunked to the negotiated maximum transfer size

**Comment by convolvatron** [comment]
sorry -how do I run this to make sure that its fixed? there don't seem to be any real references to vfsbench in the source or online, although someone posted some results so you're not the only person to know that it exists :)

**Comment by jssmith** [comment]
There's no build process for the tests right now. I was working on a cmake-based one, but didn't finish it. I'll just add a Makefile for now.

In the interim you have to build the test by hand, e.g.:
```
gcc -std=gnu99 -I../sqlite-build/ -L../sqlite-build/.libs -o test/vfsbench test/vfsbench.c -lsqlite3
```

then

```
LD_LIBRARY_PATH=../sqlite-build/.libs ./test/vfsbench nfs4 192.168.1.57/test-1gb
```

I'm running the tests right now and the segfault is gone. Performance seems to cap out with the 8k block size at 2MB/sec. That's in comparison to using the kernel's NFS (`unix` vfs against an NFS mount) where bandwidth continues to increase as block size increases, and which obtains about 15MB/sec on random reads with 64k block size (much faster when coming from cache).

**Comment by jssmith** [comment]
Next step here is for @jssmith to add the Makefile. Then this issue will be resolved.

**Comment by convolvatron** [comment]
oh, idk why i thought this was an external tool.

the only suprise about the performance numbers is that they are so close. we are going to have some natual handicaps because of the additional copies.

the segmenter is currently operating on 8k blocks. since part of the exchange id process negotiates the maximum transfers we should be using that number instead of 8k.

nfs4 allows connection bonding, so with a little more infrastructure we can stripe reads and writes across multiple connections. that would be good for at least 2x. maybe 3.

can also pipeline segmented transfers instead of waiting for the ack each time. that could
be another 2x or more depending on the bandwidth delay product

we can also use iovecs to avoid a copy on the write side. doing so on the read side is a little more tricky since we can only guess about the size of the headers, but there is probably a solution. thats worth a bit, maybe not 2x.

we should also be caching filehandles instead of doing a lookup all the time. not worth too much, but will reduce the amount of work the server has to do.

also have no idea what the caching looks like right now

**Comment by jssmith** [comment]
Will we really have additional copies? When you're running a user-space NFS server which brings data off of the disk and sends it out on the network, then you definitely get extra copies. For our use case, where we have the NFS client running in-process with the application, I think we could have the same number of copies or possibly even fewer (depends on caching / buffering implementation).

It's beyond the scope of the present milestone, but I think we will want to get this benchmark performing at the same level as the kernel implementation when doing random reads. I'm not as sure on sequential reads since SQLite handles caching in the pager and I'm not sure it makes sense to put in in the VFS as well.

All of your suggestions for speedups make sense. My guess is that the kernel is actually only takes advantage of one or two of these and we might watch it and then decide which to pursue.

**Comment by convolvatron** [comment]
Will we really have additional copies? When you're running a user-space NFS server which brings data off of the
   disk and sends it out on the network, then you definitely get extra copies. For our use case, where we have the
   NFS client running in-process with the application, I think we could have the same number of copies or possibly
   even fewer (depends on caching / buffering implementation).

there is an additional framing copy we do. if we set things up with readv/writev that goes away.

  All of your suggestions for speedups make sense. My guess is that                                                  
  the kernel is actually only takes advantage of one or two of these                                                 
  and we might watch it and then decide which to pursue.                                                             
                                                                                                                     
i should have mentioned that pipelining only help use one connection better, if we                                   
have an unlimited number of connections that has the same effect. the other thing                                    
is that idk if the server evaluates out of order. if it does that might help,                                        
although sqlite seems pretty singly threaded.

i'm a little uneasy committing to matching the kernel without unlimited time
to investigate, but it seems like we can make up most of 7x without too much
trouble.

**Comment by jssmith** [comment]
My intuition for the order of priorities is:

1. pipeline segmented transfers
2. connection bonding
3. iovecs

However we should also do a little bit of investigation to see whether there is any other low-hanging fruit.
